/**
 * Regenerates src/data/gallery-generated.ts by scanning public/images and
 * public/videos/gallery, probing dimensions with the bundled ffmpeg binary.
 *
 * Run from the repo root:  node scripts/generate-gallery.mjs
 *
 * Add new photos to public/images and new (web-safe H.264) videos + poster
 * frames to public/videos/gallery + public/images/video-thumbs, then re-run.
 * See scripts/README-media.md for the ffmpeg commands used to prep media.
 */
import { readdirSync, writeFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { extname } from "node:path";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const FF = require("ffmpeg-static");
const IMG_DIR = "public/images";
const VID_DIR = "public/videos/gallery";

// Curated images already in GALLERY + utility/non-gallery assets to skip.
const SKIP = new Set(
  [
    "aerial-bow.jpg", "aerial-coastline.jpg", "aerial-cruising.jpg",
    "aerial-open-water.jpg", "aerial-overhead-yacht.jpg", "aerial-sandbar.jpg",
    "aerial-turquoise-water.jpg", "aerial-yacht-wake.jpg",
    "bean-point-anna-maria.jpg", "egmont-key-beach.jpg", "egmont-key-shelling.jpg",
    "egmont-key.jpg", "marina-pickup-view.jpg", "pier-77-marina.jpg",
    "yacht-front-view.jpg", "hero-poster.jpg", "topfun-hero-poster.jpg",
    "top fun logo .png", "factory pic.png", "factory.png",
    ...Array.from({ length: 33 }, (_, i) => `gallery-${String(i + 1).padStart(2, "0")}.jpg`),
  ].map((s) => s.toLowerCase()),
);

const IMG_EXT = new Set([".jpg", ".jpeg", ".png", ".webp"]);

function dims(path) {
  try {
    execFileSync(FF, ["-hide_banner", "-i", path], { stdio: ["ignore", "ignore", "pipe"] });
    return null;
  } catch (e) {
    const m = (e.stderr || "").toString().match(/,\s(\d{2,5})x(\d{2,5})/);
    return m ? { width: Number(m[1]), height: Number(m[2]) } : null;
  }
}

const PHOTO_ALTS = [
  "A day on the water with Top Fun Charters near Anna Maria Island",
  "Aboard Top Fun Charters on the Gulf of Mexico",
  "Cruising the Anna Maria Island and Bradenton coastline with Top Fun Charters",
  "Sunshine and open water on a Top Fun Charters trip",
  "A private charter day with Top Fun Charters",
  "Turquoise Gulf water on a Top Fun Charters day out",
];
const VIDEO_ALTS = [
  "Video from a Top Fun Charters day on the water near Anna Maria Island",
  "On the Gulf with Top Fun Charters",
  "A moment aboard a Top Fun Charters private yacht charter",
];

const images = [];
let ai = 0;
for (const name of readdirSync(IMG_DIR, { withFileTypes: true })
  .filter((d) => d.isFile())
  .map((d) => d.name)
  .filter((n) => IMG_EXT.has(extname(n).toLowerCase()) && !SKIP.has(n.toLowerCase()))
  .sort()) {
  const d = dims(`${IMG_DIR}/${name}`);
  if (!d) { console.warn("no dims, skipped:", name); continue; }
  images.push({
    type: "image",
    src: "/images/" + encodeURIComponent(name),
    alt: PHOTO_ALTS[ai % PHOTO_ALTS.length],
    width: d.width,
    height: d.height,
    category: "On Board & Days Out",
  });
  ai++;
}

const videos = [];
let vi = 0;
for (const name of readdirSync(VID_DIR, { withFileTypes: true })
  .filter((d) => d.isFile() && d.name.toLowerCase().endsWith(".mp4"))
  .map((d) => d.name)
  .sort()) {
  const d = dims(`${VID_DIR}/${name}`);
  videos.push({
    type: "video",
    src: `/videos/gallery/${name}`,
    poster: `/images/video-thumbs/${name.replace(/\.mp4$/i, "")}.jpg`,
    alt: VIDEO_ALTS[vi % VIDEO_ALTS.length],
    width: d ? d.width : 1280,
    height: d ? d.height : 720,
    category: "Videos",
  });
  vi++;
}

const body =
  `// AUTO-GENERATED by scripts/generate-gallery.mjs. Do not edit by hand.\n` +
  `// Regenerate after adding files to public/images or public/videos/gallery.\n` +
  `import type { GalleryMedia } from "@/data/gallery";\n\n` +
  `export const GENERATED_MEDIA: GalleryMedia[] = ${JSON.stringify([...videos, ...images], null, 2)};\n`;

writeFileSync("src/data/gallery-generated.ts", body);
console.log(`Wrote ${images.length} images + ${videos.length} videos to src/data/gallery-generated.ts`);
