// AUTO-GENERATED by scripts/generate-gallery.mjs. Do not edit by hand.
// Regenerate after adding files to public/images or public/videos/gallery.
import type { GalleryMedia } from "@/data/gallery";

export const GENERATED_MEDIA: GalleryMedia[] = [
  {
    "type": "video",
    "src": "/videos/gallery/gallery-video-01.mp4",
    "poster": "/images/video-thumbs/gallery-video-01.jpg",
    "alt": "Video from a Top Fun Charters day on the water near Anna Maria Island",
    "width": 1280,
    "height": 720,
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "/videos/gallery/gallery-video-02.mp4",
    "poster": "/images/video-thumbs/gallery-video-02.jpg",
    "alt": "On the Gulf with Top Fun Charters",
    "width": 720,
    "height": 1280,
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "/videos/gallery/gallery-video-03.mp4",
    "poster": "/images/video-thumbs/gallery-video-03.jpg",
    "alt": "A moment aboard a Top Fun Charters private yacht charter",
    "width": 720,
    "height": 1280,
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "/videos/gallery/gallery-video-04.mp4",
    "poster": "/images/video-thumbs/gallery-video-04.jpg",
    "alt": "Video from a Top Fun Charters day on the water near Anna Maria Island",
    "width": 720,
    "height": 1280,
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "/videos/gallery/gallery-video-05.mp4",
    "poster": "/images/video-thumbs/gallery-video-05.jpg",
    "alt": "On the Gulf with Top Fun Charters",
    "width": 1280,
    "height": 720,
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "/videos/gallery/gallery-video-06.mp4",
    "poster": "/images/video-thumbs/gallery-video-06.jpg",
    "alt": "A moment aboard a Top Fun Charters private yacht charter",
    "width": 1280,
    "height": 720,
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "/videos/gallery/gallery-video-07.mp4",
    "poster": "/images/video-thumbs/gallery-video-07.jpg",
    "alt": "Video from a Top Fun Charters day on the water near Anna Maria Island",
    "width": 960,
    "height": 720,
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "/videos/gallery/gallery-video-08.mp4",
    "poster": "/images/video-thumbs/gallery-video-08.jpg",
    "alt": "On the Gulf with Top Fun Charters",
    "width": 720,
    "height": 1280,
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "/videos/gallery/gallery-video-09.mp4",
    "poster": "/images/video-thumbs/gallery-video-09.jpg",
    "alt": "A moment aboard a Top Fun Charters private yacht charter",
    "width": 720,
    "height": 1280,
    "category": "Videos"
  },
  {
    "type": "video",
    "src": "/videos/gallery/gallery-video-10.mp4",
    "poster": "/images/video-thumbs/gallery-video-10.jpg",
    "alt": "Video from a Top Fun Charters day on the water near Anna Maria Island",
    "width": 718,
    "height": 724,
    "category": "Videos"
  },
  {
    "type": "image",
    "src": "/images/10354b78-8623-43c0-a46e-ec5abdf3e7f7.jpg",
    "alt": "A day on the water with Top Fun Charters near Anna Maria Island",
    "width": 4032,
    "height": 3024,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/46b024ea-7165-47aa-9e1c-878e5193daa3.jpg",
    "alt": "Aboard Top Fun Charters on the Gulf of Mexico",
    "width": 2048,
    "height": 1365,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/9b0d4b23-4ad9-4f9c-a4ca-32374e72c258.jpg",
    "alt": "Cruising the Anna Maria Island and Bradenton coastline with Top Fun Charters",
    "width": 4032,
    "height": 3024,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/IMG_0022.JPG.jpeg",
    "alt": "Sunshine and open water on a Top Fun Charters trip",
    "width": 5184,
    "height": 3456,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/IMG_0032.JPEG",
    "alt": "A private charter day with Top Fun Charters",
    "width": 2048,
    "height": 1536,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/IMG_0034.JPEG",
    "alt": "Turquoise Gulf water on a Top Fun Charters day out",
    "width": 2048,
    "height": 1536,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/IMG_0037.JPEG",
    "alt": "A day on the water with Top Fun Charters near Anna Maria Island",
    "width": 2048,
    "height": 1536,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/IMG_0039.JPEG",
    "alt": "Aboard Top Fun Charters on the Gulf of Mexico",
    "width": 2048,
    "height": 1536,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/IMG_0042.JPG",
    "alt": "Cruising the Anna Maria Island and Bradenton coastline with Top Fun Charters",
    "width": 2700,
    "height": 1800,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/IMG_0046.JPG.jpeg",
    "alt": "Sunshine and open water on a Top Fun Charters trip",
    "width": 5184,
    "height": 3456,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/IMG_0051.JPG",
    "alt": "A private charter day with Top Fun Charters",
    "width": 1536,
    "height": 2048,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/IMG_0052.JPG.jpeg",
    "alt": "Turquoise Gulf water on a Top Fun Charters day out",
    "width": 480,
    "height": 320,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/IMG_0054.JPG",
    "alt": "A day on the water with Top Fun Charters near Anna Maria Island",
    "width": 2700,
    "height": 1800,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/IMG_0068.JPG",
    "alt": "Aboard Top Fun Charters on the Gulf of Mexico",
    "width": 2700,
    "height": 1800,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/IMG_0089.JPG.jpeg",
    "alt": "Cruising the Anna Maria Island and Bradenton coastline with Top Fun Charters",
    "width": 5184,
    "height": 3456,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/IMG_0095.JPG",
    "alt": "Sunshine and open water on a Top Fun Charters trip",
    "width": 2048,
    "height": 1536,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/IMG_0096.JPG.jpeg",
    "alt": "A private charter day with Top Fun Charters",
    "width": 5184,
    "height": 3456,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/IMG_0098.JPG.jpeg",
    "alt": "Turquoise Gulf water on a Top Fun Charters day out",
    "width": 480,
    "height": 320,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/IMG_0129.JPG",
    "alt": "A day on the water with Top Fun Charters near Anna Maria Island",
    "width": 2700,
    "height": 1800,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/IMG_0130.JPG.jpeg",
    "alt": "Aboard Top Fun Charters on the Gulf of Mexico",
    "width": 5184,
    "height": 3456,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/IMG_0131.JPG.jpeg",
    "alt": "Cruising the Anna Maria Island and Bradenton coastline with Top Fun Charters",
    "width": 5184,
    "height": 3456,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/IMG_0133.JPG.jpeg",
    "alt": "Sunshine and open water on a Top Fun Charters trip",
    "width": 5184,
    "height": 3456,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/IMG_0159.JPG.jpeg",
    "alt": "A private charter day with Top Fun Charters",
    "width": 5184,
    "height": 3456,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/IMG_0191.JPG.jpeg",
    "alt": "Turquoise Gulf water on a Top Fun Charters day out",
    "width": 1280,
    "height": 854,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/IMG_0196.JPG.jpeg",
    "alt": "A day on the water with Top Fun Charters near Anna Maria Island",
    "width": 5184,
    "height": 3456,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/IMG_0197.JPG.jpeg",
    "alt": "Aboard Top Fun Charters on the Gulf of Mexico",
    "width": 5184,
    "height": 3456,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/IMG_0202.JPG.jpeg",
    "alt": "Cruising the Anna Maria Island and Bradenton coastline with Top Fun Charters",
    "width": 5184,
    "height": 3456,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/IMG_0204.JPG",
    "alt": "Sunshine and open water on a Top Fun Charters trip",
    "width": 1800,
    "height": 2700,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/IMG_0230.JPG",
    "alt": "A private charter day with Top Fun Charters",
    "width": 2700,
    "height": 1800,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/IMG_0286.JPG.jpeg",
    "alt": "Turquoise Gulf water on a Top Fun Charters day out",
    "width": 1280,
    "height": 854,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/IMG_0333.JPG.jpeg",
    "alt": "A day on the water with Top Fun Charters near Anna Maria Island",
    "width": 5184,
    "height": 3456,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/IMG_0402.JPG",
    "alt": "Aboard Top Fun Charters on the Gulf of Mexico",
    "width": 2700,
    "height": 1800,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/IMG_0468.JPEG",
    "alt": "Cruising the Anna Maria Island and Bradenton coastline with Top Fun Charters",
    "width": 2048,
    "height": 1536,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/IMG_0478.JPG",
    "alt": "Sunshine and open water on a Top Fun Charters trip",
    "width": 2700,
    "height": 1801,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/IMG_0496.JPEG",
    "alt": "A private charter day with Top Fun Charters",
    "width": 2048,
    "height": 1536,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/IMG_3309.JPEG",
    "alt": "Turquoise Gulf water on a Top Fun Charters day out",
    "width": 2048,
    "height": 1536,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/IMG_3743.JPEG",
    "alt": "A day on the water with Top Fun Charters near Anna Maria Island",
    "width": 2048,
    "height": 1536,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/IMG_3979.JPEG",
    "alt": "Aboard Top Fun Charters on the Gulf of Mexico",
    "width": 2048,
    "height": 1536,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/IMG_3998.JPEG",
    "alt": "Cruising the Anna Maria Island and Bradenton coastline with Top Fun Charters",
    "width": 2048,
    "height": 1536,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/IMG_4010.JPEG",
    "alt": "Sunshine and open water on a Top Fun Charters trip",
    "width": 2048,
    "height": 1536,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/IMG_4874.JPEG",
    "alt": "A private charter day with Top Fun Charters",
    "width": 2048,
    "height": 1536,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/IMG_5603.JPEG",
    "alt": "Turquoise Gulf water on a Top Fun Charters day out",
    "width": 1536,
    "height": 2048,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/IMG_5623.JPEG",
    "alt": "A day on the water with Top Fun Charters near Anna Maria Island",
    "width": 2048,
    "height": 1536,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/IMG_5658.JPEG",
    "alt": "Aboard Top Fun Charters on the Gulf of Mexico",
    "width": 2048,
    "height": 1536,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/IMG_5671.JPEG",
    "alt": "Cruising the Anna Maria Island and Bradenton coastline with Top Fun Charters",
    "width": 2048,
    "height": 1536,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/IMG_6643.JPEG",
    "alt": "Sunshine and open water on a Top Fun Charters trip",
    "width": 2048,
    "height": 1536,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/IMG_6979.JPEG",
    "alt": "A private charter day with Top Fun Charters",
    "width": 2048,
    "height": 1536,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/IMG_6983.JPEG",
    "alt": "Turquoise Gulf water on a Top Fun Charters day out",
    "width": 1536,
    "height": 2048,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/IMG_6991.JPEG",
    "alt": "A day on the water with Top Fun Charters near Anna Maria Island",
    "width": 1536,
    "height": 2048,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/IMG_6992.JPEG",
    "alt": "Aboard Top Fun Charters on the Gulf of Mexico",
    "width": 2048,
    "height": 1536,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/IMG_7199.JPEG",
    "alt": "Cruising the Anna Maria Island and Bradenton coastline with Top Fun Charters",
    "width": 2048,
    "height": 1536,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/IMG_7204.JPEG",
    "alt": "Sunshine and open water on a Top Fun Charters trip",
    "width": 2048,
    "height": 1536,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/IMG_7482.JPEG",
    "alt": "A private charter day with Top Fun Charters",
    "width": 2048,
    "height": 1536,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/IMG_7504.jpeg",
    "alt": "Turquoise Gulf water on a Top Fun Charters day out",
    "width": 1280,
    "height": 959,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/IMG_7505.jpeg",
    "alt": "A day on the water with Top Fun Charters near Anna Maria Island",
    "width": 1280,
    "height": 960,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/IMG_7506.jpeg",
    "alt": "Aboard Top Fun Charters on the Gulf of Mexico",
    "width": 960,
    "height": 1280,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/IMG_7514.jpeg",
    "alt": "Cruising the Anna Maria Island and Bradenton coastline with Top Fun Charters",
    "width": 960,
    "height": 1280,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/IMG_7517.jpeg",
    "alt": "Sunshine and open water on a Top Fun Charters trip",
    "width": 1089,
    "height": 1420,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/IMG_7518.jpeg",
    "alt": "A private charter day with Top Fun Charters",
    "width": 1280,
    "height": 960,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/IMG_7519(1).JPEG",
    "alt": "Turquoise Gulf water on a Top Fun Charters day out",
    "width": 2048,
    "height": 1536,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/IMG_7519.jpeg",
    "alt": "A day on the water with Top Fun Charters near Anna Maria Island",
    "width": 1280,
    "height": 960,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/IMG_7521(1).JPEG",
    "alt": "Aboard Top Fun Charters on the Gulf of Mexico",
    "width": 2048,
    "height": 1535,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/IMG_7523(1).JPEG",
    "alt": "Cruising the Anna Maria Island and Bradenton coastline with Top Fun Charters",
    "width": 2037,
    "height": 1545,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/IMG_7523.jpeg",
    "alt": "Sunshine and open water on a Top Fun Charters trip",
    "width": 1280,
    "height": 971,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/IMG_7525.jpeg",
    "alt": "A private charter day with Top Fun Charters",
    "width": 1324,
    "height": 673,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/IMG_7526.jpeg",
    "alt": "Turquoise Gulf water on a Top Fun Charters day out",
    "width": 1280,
    "height": 960,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/IMG_7532.jpeg",
    "alt": "A day on the water with Top Fun Charters near Anna Maria Island",
    "width": 960,
    "height": 1280,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/IMG_7536.jpeg",
    "alt": "Aboard Top Fun Charters on the Gulf of Mexico",
    "width": 960,
    "height": 1280,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/IMG_7864.JPEG",
    "alt": "Cruising the Anna Maria Island and Bradenton coastline with Top Fun Charters",
    "width": 2048,
    "height": 1536,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/IMG_7867.JPEG",
    "alt": "Sunshine and open water on a Top Fun Charters trip",
    "width": 2048,
    "height": 1536,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/IMG_8487.JPEG",
    "alt": "A private charter day with Top Fun Charters",
    "width": 2049,
    "height": 1534,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/IMG_8490.JPG",
    "alt": "Turquoise Gulf water on a Top Fun Charters day out",
    "width": 1379,
    "height": 2048,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/IMG_8491.JPG",
    "alt": "A day on the water with Top Fun Charters near Anna Maria Island",
    "width": 960,
    "height": 1706,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/IMG_8494.JPG",
    "alt": "Aboard Top Fun Charters on the Gulf of Mexico",
    "width": 1536,
    "height": 2048,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/IMG_8495.JPG",
    "alt": "Cruising the Anna Maria Island and Bradenton coastline with Top Fun Charters",
    "width": 1536,
    "height": 2048,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/a4435b18-63a6-47f9-81ba-e067684055ca.jpg",
    "alt": "Sunshine and open water on a Top Fun Charters trip",
    "width": 2047,
    "height": 1365,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/austin%20top%20fun.webp",
    "alt": "A private charter day with Top Fun Charters",
    "width": 382,
    "height": 510,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/drone%202.jpeg",
    "alt": "Turquoise Gulf water on a Top Fun Charters day out",
    "width": 1920,
    "height": 1080,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/eggmont%203.jpg",
    "alt": "A day on the water with Top Fun Charters near Anna Maria Island",
    "width": 1200,
    "height": 900,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/formula%20splash.jpg",
    "alt": "Aboard Top Fun Charters on the Gulf of Mexico",
    "width": 4032,
    "height": 3024,
    "category": "On Board & Days Out"
  },
  {
    "type": "image",
    "src": "/images/formula8.jpg",
    "alt": "Cruising the Anna Maria Island and Bradenton coastline with Top Fun Charters",
    "width": 4032,
    "height": 3024,
    "category": "On Board & Days Out"
  }
];
